# Generated by Django 4.2.1 on 2024-05-17 04:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricPole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole_ID', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PoleInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='map_display.device')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='map_display.electricpole')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricPoleConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='map_display.electricpole')),
                ('pole_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='map_display.electricpole')),
            ],
        ),
    ]
