# Generated by Django 4.2.1 on 2024-05-07 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0006_electricline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_connections', to='map_display.electricpole')),
                ('source_pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to='map_display.electricpole')),
            ],
        ),
    ]
