# Generated by Django 4.2.1 on 2024-05-07 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0007_electricconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricPoleConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='map_display.electricpole')),
                ('pole_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='map_display.electricpole')),
            ],
            options={
                'verbose_name': 'Electric Pole Connection',
                'verbose_name_plural': 'Electric Pole Connections',
            },
        ),
        migrations.DeleteModel(
            name='ElectricConnection',
        ),
    ]
