# Generated by Django 4.2.1 on 2024-05-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0008_electricpoleconnection_delete_electricconnection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricpoleconnection',
            options={},
        ),
    ]
