# Generated by Django 4.2.1 on 2024-05-07 06:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0009_alter_electricpoleconnection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricpoleconnection',
            name='line',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
