# Generated by Django 4.2.1 on 2024-05-07 06:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0010_electricpoleconnection_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricpoleconnection',
            old_name='line',
            new_name='connection_line',
        ),
        migrations.AlterField(
            model_name='electricline',
            name='path',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
