# Generated by Django 4.2.1 on 2024-05-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0011_rename_line_electricpoleconnection_connection_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricpoleconnection',
            name='connection_line',
        ),
    ]
