# Generated by Django 4.2.1 on 2024-05-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0012_remove_electricpoleconnection_connection_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='names',
        ),
    ]
