# Generated by Django 4.2.1 on 2024-05-07 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0013_rename_name_restaurant_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='names',
            new_name='name',
        ),
    ]
