# Generated by Django 4.2.1 on 2024-05-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0014_rename_names_restaurant_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectricLine',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.RenameField(
            model_name='electricpole',
            old_name='name',
            new_name='pole_ID',
        ),
    ]
