# Generated by Django 4.2.1 on 2024-05-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0015_delete_electricline_delete_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricpole',
            name='location',
        ),
        migrations.AddField(
            model_name='electricpole',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricpole',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
