# Generated by Django 4.2.1 on 2024-05-14 05:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0016_remove_electricpole_location_electricpole_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricpole',
            old_name='pole_ID',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='electricpole',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='electricpole',
            name='longitude',
        ),
        migrations.AddField(
            model_name='electricpole',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
