# Generated by Django 4.2.1 on 2024-05-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0017_rename_pole_id_electricpole_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricpole',
            old_name='name',
            new_name='pole_ID',
        ),
        migrations.RemoveField(
            model_name='electricpole',
            name='location',
        ),
        migrations.AddField(
            model_name='electricpole',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricpole',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
