# Generated by Django 4.2.1 on 2024-05-14 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0018_rename_name_electricpole_pole_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoleInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='map_display.electricpole')),
            ],
        ),
    ]
