# Generated by Django 4.2.1 on 2024-05-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0019_poleinstallation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WireType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='PoleInstallation',
        ),
        migrations.AddField(
            model_name='electricpole',
            name='wire_types',
            field=models.ManyToManyField(blank=True, related_name='electric_poles', to='map_display.wiretype'),
        ),
    ]
