# Generated by Django 4.2.1 on 2024-05-14 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0020_wiretype_delete_poleinstallation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoleInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='electricpole',
            name='wire_types',
        ),
        migrations.DeleteModel(
            name='WireType',
        ),
        migrations.AddField(
            model_name='poleinstallation',
            name='pole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='map_display.electricpole'),
        ),
    ]
