# Generated by Django 4.2.1 on 2024-05-15 06:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0021_poleinstallation_remove_electricpole_wire_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricpole',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
