# Generated by Django 4.2.1 on 2024-05-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0022_electricpole_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricpole',
            name='location',
        ),
    ]
