# Generated by Django 4.2.1 on 2024-05-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0024_electricpole_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricpole',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='electricpole',
            name='longitude',
        ),
    ]
