# Generated by Django 4.2.1 on 2024-05-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0026_electricpole_latitude_electricpole_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricpole',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='electricpole',
            name='longitude',
        ),
    ]
